[
{"name": "Cheetos", "Calories": 160, "Carbs": "15g", "Allergens": "Milk, Cheese, Whey", "Diet Info": "Cholesterol Free, Gluten Free"},
{"name": "Lays Potato Chips", "Calories": 160, "Carbs": "15g", "Allergens": "Allergen Free", "Diet Info": "Cholesterol Free, Gluten Free" },
{"name": "Quaker Granola Bars (Chocolate Chip)", "Calories": 100, "Carbs": "17g", "Allergens": "Tree Nuts, Nuts, Milk, Soy, Soybean, Wheat, Barley, Oats", "Diet Info": "Cholesterol Free, Low Sodium" },
{"name":"Rice Krispy Treats", "Calories": 130, "Carbs":"29g", "Allergens":"Malt", "Diet Info": "Cholesterol free, Fat Free" },
{"name":"Cheez-Its", "Calories": 150, "Carbs":"17g", "Allergens":"Milk, Cheese, Soy, Whey, Wheat", "Diet Info": "Cholesterol free, Sugar Free" },
{"name":"Oreos", "Calories": 160, "Carbs":"25g", "Allergens":"Soya, Dairy,", "Diet Info": "Cholesterol Free, Low Sodium" },
{"name":"Pringles", "Calories": 150, "Carbs":"15g", "Allergens":"Milk, Butter, Caseinates, Whey, Soybean, Wheat", "Diet Info": "Cholesterol free" },
{"name":"Snyder's Pretzel Minis", "Calories": 110, "Carbs":"25g", "Allergens":"Wheat, Malt", "Diet Info": "Cholesterol Free, Fat Free, Saturated Fat free" },
{"name":"Welch's Fruit Snacks", "Calories": 88, "Carbs":"22g", "Allergens":"Allergen free", "Diet Info": "Cholesterol Free, Fat Free, Saturated Fat Free, Low Sodium" },
{"name":"Hershey's Kisses", "Calories": 200, "Carbs":"25g", "Allergens":"Milk, Lactose, Soy", "Diet Info": "Low Cholesterol, Low Sodium" },
{"name":"Coke", "Calories": 140, "Carbs":"39g", "Allergens":"Allergen Free", "Diet Info": "Fat Free, Gluten Free, Low Sodium" },
{"name":"Diet Coke", "Calories": 0, "Carbs":"0.4g", "Allergens":"Allergen Free", "Diet Info": "Gluten Free, Calorie Free, Fat free, Cholesterol Free, Saturated Fat Free, Low Sodium, Sugar Free" },
{"name":"Sprite", "Calories": 140, "Carbs":"38g", "Allergens":"Allergen Free", "Diet Info": "Fat Free, Gluten Free" },
{"name":"Sprite Zero", "Calories": 0, "Carbs":"0g", "Allergens":"Allergen Free", "Diet Info": "Fat Free, Calorie Free, Gluten Free, Low Sodium" },
{"name":"Pure Leaf Tea House Collection Organic Black Tea Wild Blackberry & Sage", "Calories": 90, "Carbs":"21", "Allergens":"Allergen Free", "Diet Info": "Gluten Free, Fat Free" },
{"name":"Minute Maid Orange Juice", "Calories": 110, "Carbs":"26g", "Allergens":"Allergen Free", "Diet Info": "Gluten Free, fat free, Low Sodium" },
{"name":"Minute Maid Apple Juice", "Calories": 80, "Carbs":"21g", "Allergens":"Allergen Free", "Diet Info": "Gluten Free, " },
{"name":"LaCroix", "Calories": 0, "Carbs":"0g", "Allergens":"Allergen Free", "Diet Info": "Gluten Free" },
{"name":"Lindt Hello My Name Is mango Smoothie", "Calories": 210, "Carbs":"22g", "Allergens":"Milk, Lactose, Soya, Wheat", "Diet Info": "Low Sodium, Low Cholesterol" },
{"name":"Starbucks Coffee Coffee Drink Premium Energy, Cinnamon Dulce", "Calories": 110, "Carbs":"18", "Allergens":"Milk", "Diet Info": "Low Cholesterol, Low Fat, Low Sodium, Low Saturated Fat, Good source of Protein" },
]
